### ISSUE TITLE
Scraping a user's followers

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#10]
I would like to scrape a user's followers to create a network diagram of users.

**Comment by haccer** [comment]
This isn't possible via Twitter's search feature.

**Comment by DonaldTsang** [comment]
@haccer But it is possible to scrape a user's follows/followers list.  
Example 1: https://twitter.com/jordanbpeterson/following  
Example 2: https://twitter.com/jordanbpeterson/followers
