### ISSUE TITLE
Does not work with some twitter accounts

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#13]
Twitter accounts with `This profile may include potentially sensitive content`on the front,  
where you have to click into it to access the content, will break tweep.  
It will have a button that look like  
`<button class="EdgeButton EdgeButton--tertiary ProfileWarningTimeline-button">Yes, view profile</button>`

**Comment by haccer** [comment]
This does not seem to be a real issue.

The `This profile may include potentially sensitive content` does not correlate at all with Tweep for 2 reasons:
- Tweep does not make requests to a person's profile, it uses Twitter's search.
- Content preferences are dictated by the authenticated user's settings, Tweep does not authenticate you.

I tested Tweep with several porn star Twitter accounts containing sensitive content, and it worked just fine.

**Comment by DonaldTsang** [comment]
Maybe I was doing it wrong. Would you mind giving me the instructions in higher detail?

**Comment by haccer** [comment]
Sure,

- Grab the latest version
- make sure you have Python3.5 or higher installed
- `pip install -r requirements.txt`
- `python3 tweep.py -u twitterhandlehere`

**Comment by pachonk** [comment]
@DonaldTsang It would also help if you showed how you did it, the error messages, etc. and what the expected results are.
The body of your issue doesn't make much sense in the context of this app since it uses the search functionality of twitter, but I could be wrong

**Comment by DonaldTsang** [comment]
@haccer @pachonk 
Got it, since I did this in the Club Room of my school, I will show you the errors.

**Comment by DonaldTsang** [comment]
@haccer @pachonk 
I tested it out, it did work with Kim Dotcom's twitter account (among others),  
but it does not work with https://twitter.com/a_fellow_white?lang=en
