### ISSUE TITLE
Custom percent-sign output format and/or CSV support

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#16]
Assuming that the data downloaded from twitter are uniformed "tuples", is it possible to format the text into a CSV format for compatibility and easy formatting?  
One of the major problem though is that according to RFC4180, double quotes, commas and newlines all requires escape characters.
If not, it would be nice if people are allowed to use percent-escape form (like the `date` bash function) to customize to their own needs.  
This idea came from https://github.com/jonbakerfish/TweetScraper where they literally have MongoDB as part of their application, such that everything is in a regular and organized manner.

**Comment by haccer** [comment]
Okay, write to csv added in latest commit.
