### ISSUE TITLE
Extract user tweets by userID instead of name/handle

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#17]
If I have a list of twitter users I have to scrape, but the list is in ID instead of handles, is it possible to use a converter like https://tweeterid.com/ to do the conversion?  
Twitter has an official solution, that is scraping a redirect from `https://twitter.com/intent/user?user_id=${number}`, however there is no shortcut for the search bar to do it.

**Comment by haccer** [comment]
Okay, I can add this

**Comment by DonaldTsang** [comment]
In Bash you can do it like `name=$(curl https://twitter.com/intent/user?user_id=${ID} | grep -Po (?<=url alternate-context" href=")\/[A-za-z0-9_]+(?=c))`

**Comment by DonaldTsang** [comment]
```
import urllib.request
def id_gen(id):
	response = urllib.request.urlopen("https://twitter.com/intent/user?user_id="+id)
	html = response.read().decode()
	return re.search('(?<=url alternate-context" href=")\/[A-za-z0-9_]+(?=c)', html).group(0)
```

**Comment by haccer** [comment]
I'll add it when I have the time.

**Comment by haccer** [comment]
Added in latest [commit](https://github.com/haccer/tweep/commit/0dc66fdf8ccb9b65be4222cfebbf6c5500d897e0).
