### ISSUE TITLE
Ability to stop after extracting N tweets

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#18]
Suppose one twitter user posts a lot, is it possible to stop the loop after N latest tweets (with other parameters) are being downloaded?

**Comment by haccer** [comment]
I can add this too

**Comment by haccer** [comment]
Added in latest [commit](https://github.com/haccer/tweep/commit/0dc66fdf8ccb9b65be4222cfebbf6c5500d897e0).
