### ISSUE TITLE
Replace comma separator in csv format by 'pipe'

### ISSUE THREAD

**Issue by hpiedcoq** [haccer/tweep#20]
Hi,

May I suggest to replace the "," separator in the csv format by "|" ? or simply quote the fields of the csv file.
The comma is difficult to interpret when there are commas in the tweet message itself.

I love this tool. Thanks.

**Comment by haccer** [comment]
Yes, 

Changed in the latest [commit](https://github.com/haccer/tweep/commit/3557ca9ec2728b07d795ffd16c8aad70eb8c73dd).

Thanks.
