### ISSUE TITLE
multiple search

### ISSUE THREAD

**Issue by m4k2000** [haccer/tweep#22]
hi, is possible to do a search with multiple key with 'and' & 'or' operators?

**Comment by pachonk** [comment]
As per the docs that's not a current feature.

**Comment by haccer** [comment]
Yeah, if I'm understanding your question correctly.

You can achieve that by doing:
`-s "search1 AND search2"`

**Comment by jamestch** [comment]
did   -s   "search1 OR search2" work？I find it seem does not work，anyone who knows why?

**Comment by pielco11** [comment]
@jamestch it works in my cases, may you be more specific?
