### ISSUE TITLE
Scrape tweets from city 

### ISSUE THREAD

**Issue by feribanez** [haccer/tweep#34]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Tweep.

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.

python tweep.py -s hello -g -38.416097,-63.616671999999994,100km -o file.csv --csv

### Description of Issue
I'd like to scrape tweets from the city of Buenos Aires. When a try it, I get this error:

usage: python3 tweep.py [options]
tweep.py: error: argument -g: expected one argument

How can I solve it?

### OS Details
Using Windows, Linux? What OS version?
Windows

**Comment by hpiedcoq** [comment]
Oh I see. The minus sign on both lat,lon messes the argument.
Let me figure out how to bypass this.

**Comment by hpiedcoq** [comment]
the minus sign is seen as an argument indeed.

To bypass this problem, use : 

`python3 tweep.py -s hello -g " -38.416097,-63.616671999999994,100km" -o file.csv --csv`

Or best said,  quote your lat/lon/range and add a space between the first quote and the lat.

It works, on my machine. Tested right now.

**Comment by hpiedcoq** [comment]
I'll modify the README file to precise this tonight.
