### ISSUE TITLE
friends and followers

### ISSUE THREAD

**Issue by marcodel13** [haccer/tweep#38]
Hi, 

do you think the code could be easily extended to mine also the followers and friends of a (list of) user?

Thanks

**Comment by haccer** [comment]
The number of followers or all of a users followers?

**Comment by marcodel13** [comment]
not the number, the list of the users.

**Comment by haccer** [comment]
Oh yeah, the only way to do that as far as I know is to launch a browser and emulate the scroll bar w/ selenium which is very resource intensive and slow.. not really something I want to add until I figure out a more sensible approach. Sorry

**Comment by pachonk** [comment]
https://twitter.com/*****/followers/users?include_available_features=1&include_entities=1&max_position=1591583889095442264&reset_error_state=false

If you can figure out how to calculate max_position, you can probably scrape this.

**Comment by marcodel13** [comment]
Hi, 

thanks! this sounds interesting, even if I honestly do not know how to do what you suggest. But I'll look into this. If you have further suggestion, please let me know!

**Comment by haccer** [comment]
Added ability to scrape followers, follows, and likes in the latest update

**Comment by AntonioNieto92** [comment]
is there a way to scrape followers quicklier?. This is because I have to scrape an account which has more than 10k followers.

Thanks in advance!

**Comment by pielco11** [comment]
@AntonioNieto92 there isn't, AFAIK
