### ISSUE TITLE
Doesn't scrap tweets till the specified date

### ISSUE THREAD

**Issue by IamRaviTejaG** [haccer/tweep#44]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Tweep.

### Command
`python tweep.py -s Bitcoin --since 2018-01-01 -0 file.csv --csv`

### Description of Issue
The module stops scraping tweets beyond a certain time frame, whereas it is expected to scrap all posts since 1st of January as mentioned in the command line args.
Example: If the latest tweet was on 2018-03-16 21:30:57 IST, the module retrieves tweets till about 2018-03-16 06:54:15 IST.

### OS Details
OS Name: Microsoft Windows 10 Home Single Language
OS Version: 10.0.16299 N/A Build 16299

**Comment by haccer** [comment]
I don't see anything wrong here.

Since means that it will collect Tweets sent since specified date, starting from the current ones.
