### ISSUE TITLE
Tweep stop scraping after about 15000/20000 tweets back

### ISSUE THREAD

**Issue by codicef** [haccer/tweep#46]
### Command
python3 tweep.py -s eurusd

### Description of Issue
I want to ask why if I start scraping for a keyword after about 10 days back the scraping process ends.
I would like to scrape at least 1000 days back
The number of scraped tweets change each time I use "python3 tweep.py -s eurusd"

### OS Details
Debian 9

**Comment by haccer** [comment]
Might be a connection issue. I plan on adding a `--resume` option in the future for those times things stop working.
