### ISSUE TITLE
Can't collect more than 213947 tweets

### ISSUE THREAD

**Issue by timothyjgraham** [haccer/tweep#48]
### Initial Check 
Make sure you've checked the following.

- [y] Python version is 3.5 or higher.
- [y] Using the latest version of Tweep.

### Command
tweep.py -s #metoo --since 2017-10-01 --stats --count -o metoo_data.csv --csv

### Description of Issue
I am trying to collect tweets containing #MeToo since 1 October 2017, however the scraper always stops when it gets to about 213947 tweets. This means that the scraper begins at the current date, starts to scrape backwards in time, but it never gets past a few weeks of tweets because it hits the (apparent) limit.

I have tried to exclude 2018, which means that the scraper begins at 31 December 2017, but again it only manages to scrape a few weeks of tweets before it hits the limit.

Any possible solutions much appreciated. 

### OS Details
Windows 10; completely up to date.

**Comment by haccer** [comment]
Thank you, I'll look into this when I can

**Comment by haccer** [comment]
If the tweet limit is consistent, 
- Twitter could be blocking requests after x amount of requests
- That's an actual limit

For now, you could probably iterate the date as a working solution e.g. scraping in weekly chunks.

If the tweet limit is consistent, I'll add a chunking function to iterate the date in the script.

**Comment by timothyjgraham** [comment]
Hi Cody,

Thanks for the reply and suggested solutions.

> you could probably iterate the date as the working solution e.g. scraping in weekly chunks.

Could you please elaborate on which parameters I would use to achieve this? I know that there is a “since” parameter but wasn’t sure about a “to”, i.e. being able to specify a time range.

Thanks,

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by haccer** [comment]
Tim, 

I've added a new `--until` option which is similar to `--since` except it's the opposite.

So scraping it in weekly chunks would work like:
`python3 tweep.py -s "#metoo" --until 2017-10-07 --since 2017-10-01`

Which will collect from that week, then the next scrape would be:
`python3 tweep.py -s "#metoo" --until 2017-10-14 --since 2017-10-07`

So on and so forth.

I'll be working on this project a lot today, and will work towards adding a function to automate this.

**Comment by timothyjgraham** [comment]
Hi Cody,

This is great - thanks for implementing the new ‘--until’ option. I’m giving it a go now and seems to do the trick.

I am collecting data to do some comparisons of data collected via the free API versus the ground truth data. I am interested in issues relating to sampling and statistical properties of the data.

Thanks again,

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________
