### ISSUE TITLE
terminal-free usage

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#52]
### Description of Issue
The current usage of tweep requires the use of the CLI, thus in jupyter notebook `!python3 tweep.py...` is needed for use in other scripts.  
It would be great if there is a way of inputting the arg without the need for terminal calls.

**Comment by haccer** [comment]
I've been working on a separate version of Tweep for this on and off. Going to close the issue since it's not immediate, but I will definitely inform you when it's out. :D thanks
