### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by DonaldTsang** [haccer/tweep#53]
### Description of Issue
Allowing the selection of languages (e.g. English, French, German) as a parameter.
https://github.com/MasimovR/tweep/commit/d8932d7987b06e44289c72dfd1e32d46c3232cbb

**Comment by haccer** [comment]
Great suggestion @DonaldTsang! I'll add it later today

**Comment by edsu** [comment]
Maybe this isn't what you are looking for but this can be achieved with search by adding a code to your query. For example:

    twint -s 'obama lang:fr' --output twets.json --json
