### ISSUE TITLE
Tweep vs Tweepy

### ISSUE THREAD

**Issue by ScottSiegel** [haccer/tweep#54]
What are some of the **disadvantages** of using Tweep compaired to APIs that use auth such as Tweepy? The README only lists advantages. 

e.g. Will Tweep miss tweets that the Twitter API wouldn't?

**Comment by pachonk** [comment]
Tweep can fetch all tweets. Also tweep can be more secretive since you
don't need an auth token

**Comment by haccer** [comment]
Good question @scottsiegel

Disadvantages of not using Twitter API:
- Twitter API offers a wider range of data to collect in different ways.
- Tweep won’t collect retweets (yet)
- Tweep will only collect tweets visible from Twitter’s search
