### ISSUE TITLE
entry for table 'users' shows none for multiuser entry

### ISSUE THREAD

**Issue by 4sakura** [haccer/tweep#58]
when using `python3 tweep.py -s 'truedonaldtrump' --database test.db` the saved table 'users' in SQLight, contains the entry 'None' instead of the Usernames. So multiuser entries won't work.
If you use `python3 tweep.py -u 'truedonaldtrump' --database test.db` the entry of 'users' is right.
Bug or feature?

**Comment by pielco11** [comment]
Hi @4sakura , thank you for pointing out! I'm going to fix that

**Comment by 4sakura** [comment]
You can close it. I just wanted to point it out.
