### ISSUE TITLE
Possibility of downloading threads w/replies?

### ISSUE THREAD

**Issue by rinkydinkyproject** [haccer/tweep#59]
### Initial Check 
Make sure you've checked the following.

- [] Python version is 3.5 or higher.
- [] Using the latest version of Tweep.
All good here. 

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.

Looking to see if the option --to:username can be added to cover replies if possible given how the tool works. 

### Description of Issue ## This is a feature request, not so much an issue ##
IF possible a way to get an entire twitter thread started by a given user OR one a given user has participated in, helps in providing context. I understand if this is not feasible given the way the tool works, but wanted to see if that possibility had been explored. Otherwise this tool is brilliant! 

### OS Details
Using Windows, Linux? What OS version?

**Comment by haccer** [comment]
Added `--to` and `--all`

`--to` will fetch all the replies, and `--all` will fetch everything associated with that user (mentions, replies, tweets from the users)

As far as threading goes, I'll need to investigate more. It might not be doable with only 1 search.
