### ISSUE TITLE
getitem error

### ISSUE THREAD

**Issue by lorenzoromani1983** [haccer/tweep#8]
Previously I was able to use tweet. Now not anymore.
i get this error:

TypeError: 'NoneType' object has no attribute '__getitem__'

what next?

lorenzo

**Comment by pachonk** [comment]
Hope do you reproduce this error?

**Comment by lorenzoromani1983** [comment]
just typing python tweep.py -u username 
in the command line.
i have python 2.7

**Comment by pachonk** [comment]
Are you positive you have the proper dependencies installed?

**Comment by lorenzoromani1983** [comment]
yes...i do!

**Comment by lorenzoromani1983** [comment]
Solved by using linux.
do you think it is possible to modify the script in order to scrape all the followers/friends of a user, or of a list of users, in order to make a network graph without having to wait weeks? The API is really inefficient for this kind of work...

**Comment by haccer** [comment]
Oh, yeah I use linux lol.

Scraping followers is difficult, the tweets are scrapable via a trick w/ the search operators. Followers can't be scraped in that way, it'd have to involve some nasty selenium work because the only way to get a person's followers is scrolling down the list.
